version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      APP_ENV: prod
      APP_SECRET: your_secret_key
    volumes:
      - .:/var/www/html
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
